name: Deploy to AWS EC2

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          command_timeout: 30m
          script: |
            set -e

            echo "==> Go to project"
            cd ~/tuyendungJd

            echo "==> Pull latest code"
            git fetch origin master
            git reset --hard origin/master

            echo "==> Stop old containers"
            docker compose down

            echo "==> Build and start containers"
            docker compose up -d --build

            echo "==> Clean unused Docker cache/images"
            docker builder prune -af
            docker image prune -af

            echo "==> Show containers"
            docker ps

            echo "==> Show disk usage"
            df -h